apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.ui}}
  name: {{.Values.edgex.app.ui}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.ui}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
