apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.consul}}
  name: {{.Values.edgex.app.core.consul}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 8400
    protocol: TCP
    targetPort: 8400
  - name: http-1
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.core.consul}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
