apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.metadata}}
  name: {{.Values.edgex.app.core.metadata}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 48081
    protocol: TCP
    targetPort: 48081
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.core.metadata}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
