apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.metadata}}
  name: {{.Values.edgex.app.core.metadata}}
spec:
  replicas: {{.Values.edgex.replicas.core.metadata}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.core.metadata}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.core.metadata}}
    spec:
      containers:
      - name: {{.Values.edgex.app.core.metadata}}
        image: {{.Values.edgex.image.core.metadata.repository}}:{{.Values.edgex.image.core.metadata.tag}}
        imagePullPolicy: {{.Values.edgex.image.core.metadata.pullPolicy}}
        command: ["/core-metadata","-cp=consul.http://edgex-core-consul.default.svc.cluster.local:8500","--registry","--confdir=/res"]
        ports:
        - containerPort: 48081
          hostPort: 48081
        env:
        - name: Service_Host
          value: {{.Values.edgex.dnsserver.core.metadata}}
        - name:  Service_Timeout
          value: "20000"
        - name: Notifications_Sender
          value: {{.Values.edgex.dnsserver.core.metadata}}
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: edgex_registry
          value: consul://{{.Values.edgex.dnsserver.core.consul}}:8500
        - name: Registry_Host
          value: {{.Values.edgex.dnsserver.core.consul}}
        - name: Clients_CoreData_Host
          value: {{.Values.edgex.dnsserver.core.data}}
        - name:  Clients_Metadata_Host
          value: {{.Values.edgex.dnsserver.core.metadata}}
        - name: Clients_Notifications_Host
          value: {{.Values.edgex.dnsserver.support.notifications}}
        - name: Clients_Command_Host
          value: {{.Values.edgex.dnsserver.core.command}}
        - name: Clients_Scheduler_Host
          value: {{.Values.edgex.dnsserver.support.scheduler}}
        - name: Clients_RulesEngine_Host
          value: {{.Values.edgex.dnsserver.support.rulesengine}}
        - name: Clients_VirtualDevice_Host
          value: {{.Values.edgex.dnsserver.device.virtual}}
        - name: Databases_Primary_Host
          value: {{.Values.edgex.dnsserver.redis}}
        - name: Logging_EnableRemote
          value: "false"
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48081
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48081
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.core.metadata.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.core.metadata.limits.memory }}
            cpu: {{ .Values.edgex.resources.core.metadata.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.core.metadata.requests.memory }}
            cpu: {{ .Values.edgex.resources.core.metadata.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.core.metadata}}
      restartPolicy: Always
status: {}
