apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
  name: {{.Values.edgex.app.device.virtual}}
spec:
  replicas: {{.Values.edgex.replicas.device.virtual}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.device.virtual}}
    spec:
      containers:
      - name: {{.Values.edgex.app.device.virtual}}
        image: {{.Values.edgex.image.device.virtual.repository}}:{{.Values.edgex.image.device.virtual.tag}}
        imagePullPolicy: {{.Values.edgex.image.device.virtual.pullPolicy}}
        ports:
        - containerPort: 49990
          hostPort: 49990
        env:
        - name: Service_Host
          value: {{.Values.edgex.dnsserver.device.virtual}}
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: edgex_registry
          value: consul://{{.Values.edgex.dnsserver.core.consul}}:8500
        - name: Registry_Host
          value: {{.Values.edgex.dnsserver.core.consul}}
        - name: Clients_CoreData_Host
          value: {{.Values.edgex.dnsserver.core.data}}
        - name:  Clients_Metadata_Host
          value: {{.Values.edgex.dnsserver.core.metadata}}
        - name: Clients_Notifications_Host
          value: {{.Values.edgex.dnsserver.support.notifications}}
        - name: Clients_Command_Host
          value: {{.Values.edgex.dnsserver.core.command}}
        - name: Clients_Scheduler_Host
          value: {{.Values.edgex.dnsserver.support.scheduler}}
        - name: Clients_RulesEngine_Host
          value: {{.Values.edgex.dnsserver.support.rulesengine}}
        - name: Clients_VirtualDevice_Host
          value: {{.Values.edgex.dnsserver.device.virtual}}
        - name: Databases_Primary_Host
          value: {{.Values.edgex.dnsserver.redis}}
        - name: Logging_EnableRemote
          value: "false"
        livenessProbe:
          tcpSocket:
            port: 49990
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 49990
          periodSeconds: 5
      {{- if .Values.edgex.resources.device.virtual.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.device.virtual.limits.memory }}
            cpu: {{ .Values.edgex.resources.device.virtual.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.device.virtual.requests.memory }}
            cpu: {{ .Values.edgex.resources.device.virtual.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.device.virtual}}
      restartPolicy: Always
status: {}
