apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.notifications}}
  name: {{.Values.edgex.app.support.notifications}}
spec:
  replicas: {{.Values.edgex.replicas.support.notifications}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.support.notifications}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.support.notifications}}
    spec:
      containers:
      - name: {{.Values.edgex.app.support.notifications}}
        image: {{.Values.edgex.image.support.notifications.repository}}:{{.Values.edgex.image.support.notifications.tag}}
        imagePullPolicy: {{.Values.edgex.image.support.notifications.pullPolicy}}
        ports:
        - containerPort: 48060
          hostPort: 48060
        env:
        - name: Service_Host
          value: {{.Values.edgex.dnsserver.support.notifications}}
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: edgex_registry
          value: consul://{{.Values.edgex.dnsserver.core.consul}}:8500
        - name: Registry_Host
          value: {{.Values.edgex.dnsserver.core.consul}}
        - name: Clients_CoreData_Host
          value: {{.Values.edgex.dnsserver.core.data}}
        - name:  Clients_Metadata_Host
          value: {{.Values.edgex.dnsserver.core.metadata}}
        - name: Clients_Notifications_Host
          value: {{.Values.edgex.dnsserver.support.notifications}}
        - name: Clients_Command_Host
          value: {{.Values.edgex.dnsserver.core.command}}
        - name: Clients_Scheduler_Host
          value: {{.Values.edgex.dnsserver.support.scheduler}}
        - name: Clients_RulesEngine_Host
          value: {{.Values.edgex.dnsserver.support.rulesengine}}
        - name: Clients_VirtualDevice_Host
          value: {{.Values.edgex.dnsserver.device.virtual}}
        - name: Databases_Primary_Host
          value: {{.Values.edgex.dnsserver.redis}}
        - name: Logging_EnableRemote
          value: "false"
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48060
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48060
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.support.notifications.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.support.notifications.limits.memory }}
            cpu: {{ .Values.edgex.resources.support.notifications.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.support.notifications.requests.memory }}
            cpu: {{ .Values.edgex.resources.support.notifications.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.support.notifications}}
      restartPolicy: Always
status: {}
