apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.scheduler}}
  name: {{.Values.edgex.app.support.scheduler}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 48085
    protocol: TCP
    targetPort: 48085
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.support.scheduler}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
