apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  name: {{.Values.edgex.app.support.rulesengine}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 48075
    protocol: TCP
    targetPort: 48075
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.support.rulesengine}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
