apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.command}}
  name: {{.Values.edgex.app.core.command}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 48082
    protocol: TCP
    targetPort: 48082
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.core.command}}
  clusterIP: None
status:
  loadBalancer: {}
