apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.redis}}
  name: {{.Values.edgex.app.redis}}
spec:
  replicas: {{.Values.edgex.replicas.redis}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.redis}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.redis}}
    spec:
      nodeSelector:
        kubernetes.io/hostname: edge-node3
      containers:
      - name: {{.Values.edgex.app.redis}}
        image: {{.Values.edgex.image.redis.repository}}:{{.Values.edgex.image.redis.tag}}
        imagePullPolicy: {{.Values.edgex.image.redis.pullPolicy}}
        ports:
        - containerPort: 6379
          hostPort: 6379
        env:
        - name: Service_Host
          value: {{.Values.edgex.dnsserver.redis}}
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: edgex_registry
          value: consul://{{.Values.edgex.dnsserver.core.consul}}:8500
        - name: Registry_Host
          value: {{.Values.edgex.dnsserver.core.consul}}
        - name: Clients_CoreData_Host
          value: {{.Values.edgex.dnsserver.core.data}}
        - name:  Clients_Metadata_Host
          value: {{.Values.edgex.dnsserver.core.metadata}}
        - name: Clients_Notifications_Host
          value: {{.Values.edgex.dnsserver.support.notifications}}
        - name: Clients_Command_Host
          value: {{.Values.edgex.dnsserver.core.command}}
        - name: Clients_Scheduler_Host
          value: {{.Values.edgex.dnsserver.support.scheduler}}
        - name: Clients_RulesEngine_Host
          value: {{.Values.edgex.dnsserver.support.rulesengine}}
        - name: Clients_VirtualDevice_Host
          value: {{.Values.edgex.dnsserver.device.virtual}}
        - name: Databases_Primary_Host
          value: {{.Values.edgex.dnsserver.redis}}
        - name: Logging_EnableRemote
          value: "false"
        livenessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
      {{- if .Values.edgex.resources.redis.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.redis.limits.memory }}
            cpu: {{ .Values.edgex.resources.redis.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.redis.requests.memory }}
            cpu: {{ .Values.edgex.resources.redis.requests.cpu }}
      {{- end}}
        volumeMounts:
        - mountPath: /data
          name: db-data
      hostname: {{.Values.edgex.app.redis}}
      restartPolicy: Always
      volumes:
      - name: db-data
status: {}
