apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.system}}
  name: {{.Values.edgex.app.system}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 48090
    protocol: TCP
    targetPort: 48090
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.system}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
