apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.rest}}
  name: {{.Values.edgex.app.device.rest}}
  namespace: default
spec:
  ports:
  - name: http-0
    port: 49986
    protocol: TCP
    targetPort: 49986
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.device.rest}}
  type: {{.Values.edgex.serviceType}}
status:
  loadBalancer: {}
